name = "Dalinar"
uuid = "a5159adb-dd7a-4dd5-9cc5-22beaf5d8a55"
authors = ["Anirudh Vemula <vvanirudh@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
